package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Book generated by hbm2java
 */
public class Book  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private Float price;
     private Integer count;
     private String author;
     private String publication;
     private String genre;
     private String language;
     private Integer rank;
     private String description;

    public Book() {
    }

	
    public Book(Product product, String name) {
        this.product = product;
        this.name = name;
    }
    public Book(Product product, String name, Float price, Integer count, String author, String publication, String genre, String language, Integer rank, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.author = author;
       this.publication = publication;
       this.genre = genre;
       this.language = language;
       this.rank = rank;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getPrice() {
        return this.price;
    }
    
    public void setPrice(Float price) {
        this.price = price;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getPublication() {
        return this.publication;
    }
    
    public void setPublication(String publication) {
        this.publication = publication;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


