package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * CartId generated by hbm2java
 */
public class CartId  implements java.io.Serializable {


     private String emailid;
     private String pid;

    public CartId() {
    }

    public CartId(String emailid, String pid) {
       this.emailid = emailid;
       this.pid = pid;
    }
   
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartId) ) return false;
		 CartId castOther = ( CartId ) other; 
         
		 return ( (this.getEmailid()==castOther.getEmailid()) || ( this.getEmailid()!=null && castOther.getEmailid()!=null && this.getEmailid().equals(castOther.getEmailid()) ) )
 && ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEmailid() == null ? 0 : this.getEmailid().hashCode() );
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         return result;
   }   


}


