package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private CartId id;
     private String type;

    public Cart() {
    }

    public Cart(CartId id, String type) {
       this.id = id;
       this.type = type;
    }
   
    public CartId getId() {
        return this.id;
    }
    
    public void setId(CartId id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


