package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private String tbl;
     private String category;
     private String subcategory;

    public Category() {
    }

    public Category(String tbl, String category, String subcategory) {
       this.tbl = tbl;
       this.category = category;
       this.subcategory = subcategory;
    }
   
    public String getTbl() {
        return this.tbl;
    }
    
    public void setTbl(String tbl) {
        this.tbl = tbl;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getSubcategory() {
        return this.subcategory;
    }
    
    public void setSubcategory(String subcategory) {
        this.subcategory = subcategory;
    }




}


