package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Datastorage generated by hbm2java
 */
public class Datastorage  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String type;
     private String company;
     private String capacity;
     private String dimention;
     private String model;
     private String compatibility;
     private String speed;
     private String color;
     private String description;

    public Datastorage() {
    }

	
    public Datastorage(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Datastorage(Product product, String name, float price, int count, String type, String company, String capacity, String dimention, String model, String compatibility, String speed, String color, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.type = type;
       this.company = company;
       this.capacity = capacity;
       this.dimention = dimention;
       this.model = model;
       this.compatibility = compatibility;
       this.speed = speed;
       this.color = color;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(String capacity) {
        this.capacity = capacity;
    }
    public String getDimention() {
        return this.dimention;
    }
    
    public void setDimention(String dimention) {
        this.dimention = dimention;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getCompatibility() {
        return this.compatibility;
    }
    
    public void setCompatibility(String compatibility) {
        this.compatibility = compatibility;
    }
    public String getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(String speed) {
        this.speed = speed;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


