package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Ethnics generated by hbm2java
 */
public class Ethnics  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String febric;
     private String brand;
     private String color;
     private String size;
     private String sleeve;
     private String ornamentalType;
     private String gender;
     private String description;

    public Ethnics() {
    }

	
    public Ethnics(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Ethnics(Product product, String name, float price, int count, String febric, String brand, String color, String size, String sleeve, String ornamentalType, String gender, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.febric = febric;
       this.brand = brand;
       this.color = color;
       this.size = size;
       this.sleeve = sleeve;
       this.ornamentalType = ornamentalType;
       this.gender = gender;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getFebric() {
        return this.febric;
    }
    
    public void setFebric(String febric) {
        this.febric = febric;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getSleeve() {
        return this.sleeve;
    }
    
    public void setSleeve(String sleeve) {
        this.sleeve = sleeve;
    }
    public String getOrnamentalType() {
        return this.ornamentalType;
    }
    
    public void setOrnamentalType(String ornamentalType) {
        this.ornamentalType = ornamentalType;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


