package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Laptop generated by hbm2java
 */
public class Laptop  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String company;
     private String series;
     private String os;
     private String screenSize;
     private String processor;
     private Integer ram;
     private Float weight;
     private String hd;
     private String model;
     private Integer modelYear;
     private String graphicCard;
     private Integer battery;
     private String color;
     private String ports;
     private String prospeed;
     private Integer procount;
     private String protype;
     private String warranty;
     private String description;

    public Laptop() {
    }

	
    public Laptop(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Laptop(Product product, String name, float price, int count, String company, String series, String os, String screenSize, String processor, Integer ram, Float weight, String hd, String model, Integer modelYear, String graphicCard, Integer battery, String color, String ports, String prospeed, Integer procount, String protype, String warranty, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.company = company;
       this.series = series;
       this.os = os;
       this.screenSize = screenSize;
       this.processor = processor;
       this.ram = ram;
       this.weight = weight;
       this.hd = hd;
       this.model = model;
       this.modelYear = modelYear;
       this.graphicCard = graphicCard;
       this.battery = battery;
       this.color = color;
       this.ports = ports;
       this.prospeed = prospeed;
       this.procount = procount;
       this.protype = protype;
       this.warranty = warranty;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    public String getScreenSize() {
        return this.screenSize;
    }
    
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize;
    }
    public String getProcessor() {
        return this.processor;
    }
    
    public void setProcessor(String processor) {
        this.processor = processor;
    }
    public Integer getRam() {
        return this.ram;
    }
    
    public void setRam(Integer ram) {
        this.ram = ram;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public String getHd() {
        return this.hd;
    }
    
    public void setHd(String hd) {
        this.hd = hd;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Integer getModelYear() {
        return this.modelYear;
    }
    
    public void setModelYear(Integer modelYear) {
        this.modelYear = modelYear;
    }
    public String getGraphicCard() {
        return this.graphicCard;
    }
    
    public void setGraphicCard(String graphicCard) {
        this.graphicCard = graphicCard;
    }
    public Integer getBattery() {
        return this.battery;
    }
    
    public void setBattery(Integer battery) {
        this.battery = battery;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getPorts() {
        return this.ports;
    }
    
    public void setPorts(String ports) {
        this.ports = ports;
    }
    public String getProspeed() {
        return this.prospeed;
    }
    
    public void setProspeed(String prospeed) {
        this.prospeed = prospeed;
    }
    public Integer getProcount() {
        return this.procount;
    }
    
    public void setProcount(Integer procount) {
        this.procount = procount;
    }
    public String getProtype() {
        return this.protype;
    }
    
    public void setProtype(String protype) {
        this.protype = protype;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


