package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Mobiletablet generated by hbm2java
 */
public class Mobiletablet  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String model;
     private Integer ram;
     private Integer rom;
     private String screenSize;
     private Float frontCam;
     private Float rearCam;
     private Integer battery;
     private String processor;
     private String color;
     private String os;
     private String company;
     private String conTech;
     private String warranty;
     private String specialFeaturs;
     private Float weight;
     private String inbox;
     private String description;

    public Mobiletablet() {
    }

	
    public Mobiletablet(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Mobiletablet(Product product, String name, float price, int count, String model, Integer ram, Integer rom, String screenSize, Float frontCam, Float rearCam, Integer battery, String processor, String color, String os, String company, String conTech, String warranty, String specialFeaturs, Float weight, String inbox, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.model = model;
       this.ram = ram;
       this.rom = rom;
       this.screenSize = screenSize;
       this.frontCam = frontCam;
       this.rearCam = rearCam;
       this.battery = battery;
       this.processor = processor;
       this.color = color;
       this.os = os;
       this.company = company;
       this.conTech = conTech;
       this.warranty = warranty;
       this.specialFeaturs = specialFeaturs;
       this.weight = weight;
       this.inbox = inbox;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Integer getRam() {
        return this.ram;
    }
    
    public void setRam(Integer ram) {
        this.ram = ram;
    }
    public Integer getRom() {
        return this.rom;
    }
    
    public void setRom(Integer rom) {
        this.rom = rom;
    }
    public String getScreenSize() {
        return this.screenSize;
    }
    
    public void setScreenSize(String screenSize) {
        this.screenSize = screenSize;
    }
    public Float getFrontCam() {
        return this.frontCam;
    }
    
    public void setFrontCam(Float frontCam) {
        this.frontCam = frontCam;
    }
    public Float getRearCam() {
        return this.rearCam;
    }
    
    public void setRearCam(Float rearCam) {
        this.rearCam = rearCam;
    }
    public Integer getBattery() {
        return this.battery;
    }
    
    public void setBattery(Integer battery) {
        this.battery = battery;
    }
    public String getProcessor() {
        return this.processor;
    }
    
    public void setProcessor(String processor) {
        this.processor = processor;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getOs() {
        return this.os;
    }
    
    public void setOs(String os) {
        this.os = os;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getConTech() {
        return this.conTech;
    }
    
    public void setConTech(String conTech) {
        this.conTech = conTech;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getSpecialFeaturs() {
        return this.specialFeaturs;
    }
    
    public void setSpecialFeaturs(String specialFeaturs) {
        this.specialFeaturs = specialFeaturs;
    }
    public Float getWeight() {
        return this.weight;
    }
    
    public void setWeight(Float weight) {
        this.weight = weight;
    }
    public String getInbox() {
        return this.inbox;
    }
    
    public void setInbox(String inbox) {
        this.inbox = inbox;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


