package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Orderitem generated by hbm2java
 */
public class Orderitem  implements java.io.Serializable {


     private OrderitemId id;
     private Order order;
     private Product product;
     private int quantity;
     private float price;
     private String EReason;
     private String wid;

    public Orderitem() {
    }

	
    public Orderitem(OrderitemId id, Order order, Product product, int quantity, float price, String wid) {
        this.id = id;
        this.order = order;
        this.product = product;
        this.quantity = quantity;
        this.price = price;
        this.wid = wid;
    }
    public Orderitem(OrderitemId id, Order order, Product product, int quantity, float price, String EReason, String wid) {
       this.id = id;
       this.order = order;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
       this.EReason = EReason;
       this.wid = wid;
    }
   
    public OrderitemId getId() {
        return this.id;
    }
    
    public void setId(OrderitemId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getEReason() {
        return this.EReason;
    }
    
    public void setEReason(String EReason) {
        this.EReason = EReason;
    }
    public String getWid() {
        return this.wid;
    }
    
    public void setWid(String wid) {
        this.wid = wid;
    }




}


