package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * OrderitemId generated by hbm2java
 */
public class OrderitemId  implements java.io.Serializable {


     private int orderid;
     private String pid;

    public OrderitemId() {
    }

    public OrderitemId(int orderid, String pid) {
       this.orderid = orderid;
       this.pid = pid;
    }
   
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderitemId) ) return false;
		 OrderitemId castOther = ( OrderitemId ) other; 
         
		 return (this.getOrderid()==castOther.getOrderid())
 && ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrderid();
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         return result;
   }   


}


