package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private int orderid;
     private User user;
     private float amount;
     private int quantity;
     private Set orderitems = new HashSet(0);
     private Payment payment;

    public Order() {
    }

	
    public Order(int orderid, User user, float amount, int quantity) {
        this.orderid = orderid;
        this.user = user;
        this.amount = amount;
        this.quantity = quantity;
    }
    public Order(int orderid, User user, float amount, int quantity, Set orderitems, Payment payment) {
       this.orderid = orderid;
       this.user = user;
       this.amount = amount;
       this.quantity = quantity;
       this.orderitems = orderitems;
       this.payment = payment;
    }
   
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public float getAmount() {
        return this.amount;
    }
    
    public void setAmount(float amount) {
        this.amount = amount;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Set getOrderitems() {
        return this.orderitems;
    }
    
    public void setOrderitems(Set orderitems) {
        this.orderitems = orderitems;
    }
    public Payment getPayment() {
        return this.payment;
    }
    
    public void setPayment(Payment payment) {
        this.payment = payment;
    }




}


