package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private int orderid;
     private Order order;
     private Date placedate;
     private Date dispatchdate;
     private Date deliverdate;
     private String status;

    public Payment() {
    }

	
    public Payment(Order order, Date placedate, String status) {
        this.order = order;
        this.placedate = placedate;
        this.status = status;
    }
    public Payment(Order order, Date placedate, Date dispatchdate, Date deliverdate, String status) {
       this.order = order;
       this.placedate = placedate;
       this.dispatchdate = dispatchdate;
       this.deliverdate = deliverdate;
       this.status = status;
    }
   
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Date getPlacedate() {
        return this.placedate;
    }
    
    public void setPlacedate(Date placedate) {
        this.placedate = placedate;
    }
    public Date getDispatchdate() {
        return this.dispatchdate;
    }
    
    public void setDispatchdate(Date dispatchdate) {
        this.dispatchdate = dispatchdate;
    }
    public Date getDeliverdate() {
        return this.deliverdate;
    }
    
    public void setDeliverdate(Date deliverdate) {
        this.deliverdate = deliverdate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


