package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Powerbank generated by hbm2java
 */
public class Powerbank  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String company;
     private Integer capacity;
     private String model;
     private String box;
     private Integer weight;
     private String color;
     private String description;

    public Powerbank() {
    }

	
    public Powerbank(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Powerbank(Product product, String name, float price, int count, String company, Integer capacity, String model, String box, Integer weight, String color, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.company = company;
       this.capacity = capacity;
       this.model = model;
       this.box = box;
       this.weight = weight;
       this.color = color;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public String getBox() {
        return this.box;
    }
    
    public void setBox(String box) {
        this.box = box;
    }
    public Integer getWeight() {
        return this.weight;
    }
    
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


