package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String pid;
     private float discount;
     private float price;
     private String image;
     private String name;
     private Set orderitems = new HashSet(0);
     private Book book;
     private Datastorage datastorage;
     private Mobiletablet mobiletablet;
     private Tops tops;
     private Tv tv;
     private Ethnics ethnics;
     private Headphone headphone;
     private Laptop laptop;
     private Jeans jeans;
     private Set shares = new HashSet(0);
     private Powerbank powerbank;
     private Refoven refoven;
     private Set warehouses = new HashSet(0);

    public Product() {
    }

	
    public Product(String pid, float discount, float price, String name) {
        this.pid = pid;
        this.discount = discount;
        this.price = price;
        this.name = name;
    }
    public Product(String pid, float discount, float price, String image, String name, Set orderitems, Book book, Datastorage datastorage, Mobiletablet mobiletablet, Tops tops, Tv tv, Ethnics ethnics, Headphone headphone, Laptop laptop, Jeans jeans, Set shares, Powerbank powerbank, Refoven refoven, Set warehouses) {
       this.pid = pid;
       this.discount = discount;
       this.price = price;
       this.image = image;
       this.name = name;
       this.orderitems = orderitems;
       this.book = book;
       this.datastorage = datastorage;
       this.mobiletablet = mobiletablet;
       this.tops = tops;
       this.tv = tv;
       this.ethnics = ethnics;
       this.headphone = headphone;
       this.laptop = laptop;
       this.jeans = jeans;
       this.shares = shares;
       this.powerbank = powerbank;
       this.refoven = refoven;
       this.warehouses = warehouses;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public float getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(float discount) {
        this.discount = discount;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getOrderitems() {
        return this.orderitems;
    }
    
    public void setOrderitems(Set orderitems) {
        this.orderitems = orderitems;
    }
    public Book getBook() {
        return this.book;
    }
    
    public void setBook(Book book) {
        this.book = book;
    }
    public Datastorage getDatastorage() {
        return this.datastorage;
    }
    
    public void setDatastorage(Datastorage datastorage) {
        this.datastorage = datastorage;
    }
    public Mobiletablet getMobiletablet() {
        return this.mobiletablet;
    }
    
    public void setMobiletablet(Mobiletablet mobiletablet) {
        this.mobiletablet = mobiletablet;
    }
    public Tops getTops() {
        return this.tops;
    }
    
    public void setTops(Tops tops) {
        this.tops = tops;
    }
    public Tv getTv() {
        return this.tv;
    }
    
    public void setTv(Tv tv) {
        this.tv = tv;
    }
    public Ethnics getEthnics() {
        return this.ethnics;
    }
    
    public void setEthnics(Ethnics ethnics) {
        this.ethnics = ethnics;
    }
    public Headphone getHeadphone() {
        return this.headphone;
    }
    
    public void setHeadphone(Headphone headphone) {
        this.headphone = headphone;
    }
    public Laptop getLaptop() {
        return this.laptop;
    }
    
    public void setLaptop(Laptop laptop) {
        this.laptop = laptop;
    }
    public Jeans getJeans() {
        return this.jeans;
    }
    
    public void setJeans(Jeans jeans) {
        this.jeans = jeans;
    }
    public Set getShares() {
        return this.shares;
    }
    
    public void setShares(Set shares) {
        this.shares = shares;
    }
    public Powerbank getPowerbank() {
        return this.powerbank;
    }
    
    public void setPowerbank(Powerbank powerbank) {
        this.powerbank = powerbank;
    }
    public Refoven getRefoven() {
        return this.refoven;
    }
    
    public void setRefoven(Refoven refoven) {
        this.refoven = refoven;
    }
    public Set getWarehouses() {
        return this.warehouses;
    }
    
    public void setWarehouses(Set warehouses) {
        this.warehouses = warehouses;
    }




}


