package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Refoven generated by hbm2java
 */
public class Refoven  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String company;
     private String model;
     private Float energy;
     private Float capacity;
     private String color;
     private String formfactor;
     private Integer shelves;
     private String warranty;
     private String box;
     private String description;

    public Refoven() {
    }

	
    public Refoven(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Refoven(Product product, String name, float price, int count, String company, String model, Float energy, Float capacity, String color, String formfactor, Integer shelves, String warranty, String box, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.company = company;
       this.model = model;
       this.energy = energy;
       this.capacity = capacity;
       this.color = color;
       this.formfactor = formfactor;
       this.shelves = shelves;
       this.warranty = warranty;
       this.box = box;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Float getEnergy() {
        return this.energy;
    }
    
    public void setEnergy(Float energy) {
        this.energy = energy;
    }
    public Float getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Float capacity) {
        this.capacity = capacity;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getFormfactor() {
        return this.formfactor;
    }
    
    public void setFormfactor(String formfactor) {
        this.formfactor = formfactor;
    }
    public Integer getShelves() {
        return this.shelves;
    }
    
    public void setShelves(Integer shelves) {
        this.shelves = shelves;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getBox() {
        return this.box;
    }
    
    public void setBox(String box) {
        this.box = box;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


