package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * ShareId generated by hbm2java
 */
public class ShareId  implements java.io.Serializable {


     private String toEmailid;
     private String fromEmailid;
     private String pid;

    public ShareId() {
    }

    public ShareId(String toEmailid, String fromEmailid, String pid) {
       this.toEmailid = toEmailid;
       this.fromEmailid = fromEmailid;
       this.pid = pid;
    }
   
    public String getToEmailid() {
        return this.toEmailid;
    }
    
    public void setToEmailid(String toEmailid) {
        this.toEmailid = toEmailid;
    }
    public String getFromEmailid() {
        return this.fromEmailid;
    }
    
    public void setFromEmailid(String fromEmailid) {
        this.fromEmailid = fromEmailid;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ShareId) ) return false;
		 ShareId castOther = ( ShareId ) other; 
         
		 return ( (this.getToEmailid()==castOther.getToEmailid()) || ( this.getToEmailid()!=null && castOther.getToEmailid()!=null && this.getToEmailid().equals(castOther.getToEmailid()) ) )
 && ( (this.getFromEmailid()==castOther.getFromEmailid()) || ( this.getFromEmailid()!=null && castOther.getFromEmailid()!=null && this.getFromEmailid().equals(castOther.getFromEmailid()) ) )
 && ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getToEmailid() == null ? 0 : this.getToEmailid().hashCode() );
         result = 37 * result + ( getFromEmailid() == null ? 0 : this.getFromEmailid().hashCode() );
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         return result;
   }   


}


