package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Share generated by hbm2java
 */
public class Share  implements java.io.Serializable {


     private ShareId id;
     private Product product;
     private User userByFromEmailid;
     private User userByToEmailid;
     private Date sharedate;

    public Share() {
    }

    public Share(ShareId id, Product product, User userByFromEmailid, User userByToEmailid, Date sharedate) {
       this.id = id;
       this.product = product;
       this.userByFromEmailid = userByFromEmailid;
       this.userByToEmailid = userByToEmailid;
       this.sharedate = sharedate;
    }
   
    public ShareId getId() {
        return this.id;
    }
    
    public void setId(ShareId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUserByFromEmailid() {
        return this.userByFromEmailid;
    }
    
    public void setUserByFromEmailid(User userByFromEmailid) {
        this.userByFromEmailid = userByFromEmailid;
    }
    public User getUserByToEmailid() {
        return this.userByToEmailid;
    }
    
    public void setUserByToEmailid(User userByToEmailid) {
        this.userByToEmailid = userByToEmailid;
    }
    public Date getSharedate() {
        return this.sharedate;
    }
    
    public void setSharedate(Date sharedate) {
        this.sharedate = sharedate;
    }




}


