package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Tv generated by hbm2java
 */
public class Tv  implements java.io.Serializable {


     private String pid;
     private Product product;
     private String name;
     private float price;
     private int count;
     private String company;
     private String size;
     private String connectivity;
     private String warranty;
     private String modelNo;
     private String resolution;
     private String series;
     private String displayType;
     private String box;
     private String description;

    public Tv() {
    }

	
    public Tv(Product product, String name, float price, int count) {
        this.product = product;
        this.name = name;
        this.price = price;
        this.count = count;
    }
    public Tv(Product product, String name, float price, int count, String company, String size, String connectivity, String warranty, String modelNo, String resolution, String series, String displayType, String box, String description) {
       this.product = product;
       this.name = name;
       this.price = price;
       this.count = count;
       this.company = company;
       this.size = size;
       this.connectivity = connectivity;
       this.warranty = warranty;
       this.modelNo = modelNo;
       this.resolution = resolution;
       this.series = series;
       this.displayType = displayType;
       this.box = box;
       this.description = description;
    }
   
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getConnectivity() {
        return this.connectivity;
    }
    
    public void setConnectivity(String connectivity) {
        this.connectivity = connectivity;
    }
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }
    public String getModelNo() {
        return this.modelNo;
    }
    
    public void setModelNo(String modelNo) {
        this.modelNo = modelNo;
    }
    public String getResolution() {
        return this.resolution;
    }
    
    public void setResolution(String resolution) {
        this.resolution = resolution;
    }
    public String getSeries() {
        return this.series;
    }
    
    public void setSeries(String series) {
        this.series = series;
    }
    public String getDisplayType() {
        return this.displayType;
    }
    
    public void setDisplayType(String displayType) {
        this.displayType = displayType;
    }
    public String getBox() {
        return this.box;
    }
    
    public void setBox(String box) {
        this.box = box;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


