package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String emailid;
     private String password;
     private String fname;
     private String lname;
     private String phno;
     private String addr;
     private String city;
     private String state;
     private String pincode;
     private String role;
     private Set orders = new HashSet(0);
     private Set sharesForFromEmailid = new HashSet(0);
     private Set sharesForToEmailid = new HashSet(0);
     private Set warehouses = new HashSet(0);

    public User() {
    }

	
    public User(String emailid, String password, String fname, String lname, String phno, String role) {
        this.emailid = emailid;
        this.password = password;
        this.fname = fname;
        this.lname = lname;
        this.phno = phno;
        this.role = role;
    }
    public User(String emailid, String password, String fname, String lname, String phno, String addr, String city, String state, String pincode, String role, Set orders, Set sharesForFromEmailid, Set sharesForToEmailid, Set warehouses) {
       this.emailid = emailid;
       this.password = password;
       this.fname = fname;
       this.lname = lname;
       this.phno = phno;
       this.addr = addr;
       this.city = city;
       this.state = state;
       this.pincode = pincode;
       this.role = role;
       this.orders = orders;
       this.sharesForFromEmailid = sharesForFromEmailid;
       this.sharesForToEmailid = sharesForToEmailid;
       this.warehouses = warehouses;
    }
   
    public String getEmailid() {
        return this.emailid;
    }
    
    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getPhno() {
        return this.phno;
    }
    
    public void setPhno(String phno) {
        this.phno = phno;
    }
    public String getAddr() {
        return this.addr;
    }
    
    public void setAddr(String addr) {
        this.addr = addr;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }
    public Set getSharesForFromEmailid() {
        return this.sharesForFromEmailid;
    }
    
    public void setSharesForFromEmailid(Set sharesForFromEmailid) {
        this.sharesForFromEmailid = sharesForFromEmailid;
    }
    public Set getSharesForToEmailid() {
        return this.sharesForToEmailid;
    }
    
    public void setSharesForToEmailid(Set sharesForToEmailid) {
        this.sharesForToEmailid = sharesForToEmailid;
    }
    public Set getWarehouses() {
        return this.warehouses;
    }
    
    public void setWarehouses(Set warehouses) {
        this.warehouses = warehouses;
    }




}


