package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * WarehouseId generated by hbm2java
 */
public class WarehouseId  implements java.io.Serializable {


     private String wid;
     private String pid;

    public WarehouseId() {
    }

    public WarehouseId(String wid, String pid) {
       this.wid = wid;
       this.pid = pid;
    }
   
    public String getWid() {
        return this.wid;
    }
    
    public void setWid(String wid) {
        this.wid = wid;
    }
    public String getPid() {
        return this.pid;
    }
    
    public void setPid(String pid) {
        this.pid = pid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof WarehouseId) ) return false;
		 WarehouseId castOther = ( WarehouseId ) other; 
         
		 return ( (this.getWid()==castOther.getWid()) || ( this.getWid()!=null && castOther.getWid()!=null && this.getWid().equals(castOther.getWid()) ) )
 && ( (this.getPid()==castOther.getPid()) || ( this.getPid()!=null && castOther.getPid()!=null && this.getPid().equals(castOther.getPid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getWid() == null ? 0 : this.getWid().hashCode() );
         result = 37 * result + ( getPid() == null ? 0 : this.getPid().hashCode() );
         return result;
   }   


}


