package model;
// Generated Apr 8, 2017 11:28:03 PM by Hibernate Tools 4.3.1



/**
 * Warehouse generated by hbm2java
 */
public class Warehouse  implements java.io.Serializable {


     private WarehouseId id;
     private Product product;
     private User user;
     private int stock;

    public Warehouse() {
    }

    public Warehouse(WarehouseId id, Product product, User user, int stock) {
       this.id = id;
       this.product = product;
       this.user = user;
       this.stock = stock;
    }
   
    public WarehouseId getId() {
        return this.id;
    }
    
    public void setId(WarehouseId id) {
        this.id = id;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }




}


